// Libyan Areas Data - المناطق الليبية
export interface LibyanArea {
  id: string;
  name: string;
  city?: string;
}

export const libyanAreas: LibyanArea[] = [
  { id: 'deribi', name: 'الدريبي', city: 'طرابلس' },
  { id: 'sh_20_ramadan', name: 'ش 20 رمضان', city: 'بنغازي' },
  { id: 'hawamid', name: 'الحوامد', city: 'مصراتة' },
  { id: 'dhahra', name: 'الظهرة', city: 'البيضاء' },
  { id: 'laythi', name: 'الليثي', city: 'الزاوية' },
  { id: 'sayaha', name: 'السياحية', city: 'غريان' },
  { id: 'hawishi', name: 'الحويشي', city: 'طبرق' },
  { id: 'hawari', name: 'الهواري', city: 'اجدابيا' },
  { id: 'fashlum', name: 'فشلوم', city: 'زليتن' },
  { id: 'ghararat', name: 'الغرارات', city: 'درنة' },
  { id: 'fam_mulgha', name: 'فم الملغة', city: 'سرت' },
  { id: 'abu_nuwas', name: 'أبونواس', city: 'سبها' },
  { id: 'abu_salim', name: 'أبو سليم', city: 'الخمس' },
  { id: 'abu_sitta', name: 'أبو ستة', city: 'بني وليد' },
  { id: 'bumshmasha', name: 'بومشماشة', city: 'صبراتة' },
  { id: 'fakini', name: 'الفكيني', city: 'زوارة' },
  { id: 'ayn_mara', name: 'عين ماره', city: 'الكفرة' },
  { id: 'tariq_matar', name: 'طريق المطار', city: 'المرج' },
  { id: 'ghut_shaal', name: 'غوط الشعال', city: 'توكرة' },
  { id: 'qadah', name: 'قدح', city: 'ترهونة' },
  { id: 'qarqarish', name: 'قرقارش', city: 'مسلاتة' },
  { id: 'barakat', name: 'البركات', city: 'الجميل' },
  { id: 'hani', name: 'الهاني', city: 'صرمان' },
  { id: 'hashan', name: 'الحشان', city: 'القصيبات' },
  { id: 'sh_jumhuriya', name: 'ش الجمهورية', city: 'شحات' },
  { id: 'gharghur', name: 'غرغور', city: 'أوباري' },
  { id: 'karama', name: 'الكرامة', city: 'الأصابعة' },
  { id: 'ghazaya', name: 'غزايا', city: 'الجديد' },
  { id: 'sh_mamun', name: 'ش المامون', city: 'ودان' },
  { id: 'mansura', name: 'المنصورة', city: 'العقيلة' },
  { id: 'qarji', name: 'قرجي', city: 'الأبيار' },
  { id: 'sh_nasr', name: 'ش النصر', city: 'النوفلية' },
  { id: 'sh_rashid', name: 'ش الرشيد', city: 'رقدالين' },
  { id: 'siraj', name: 'السراج', city: 'قصر خيار' },
  { id: 'sh_istiqlal', name: 'شارع الاستقلال', city: 'القبة' },
  { id: 'jush', name: 'الجوش', city: 'تاورغاء' },
  { id: 'aziziya', name: 'العزيزية', city: 'الماية' },
  { id: 'hay_dollar', name: 'حي الدولار', city: 'مرزق' },
  { id: 'hadaeq', name: 'الحدائق', city: 'البريقة' },
  { id: 'allous', name: 'العلوص', city: 'تغسات' },
  { id: 'amara', name: 'العمامرة', city: 'هون' },
  { id: 'sabaa', name: 'السبعة', city: 'جالو' },
  { id: 'baz', name: 'الباز', city: 'العجيلات' },
  { id: 'watiat', name: 'الوطيات', city: 'نالوت' },
  { id: 'fallah', name: 'الفلاح', city: 'سلوق' },
  { id: 'sh_fath', name: 'شارع الفتح', city: 'شهداء البويرات' },
  { id: 'furnaj', name: 'الفرناج', city: 'زلطن' },
  { id: 'hadba', name: 'الهضبة', city: 'مزدة' },
  { id: 'haddad', name: 'الحداد', city: 'رأس لانوف' },
  { id: 'jannat', name: 'الجنات', city: 'العربان' },
  { id: 'jamil', name: 'الجميل', city: 'يفرن' },
  { id: 'karimia', name: 'الكريمية', city: 'الريانية' },
  { id: 'madina_riyadiya', name: 'المدينة الرياضية', city: 'أم الرزم' },
  { id: 'maari', name: 'المعري', city: 'تاورغاء' },
  { id: 'majuri', name: 'الماجوري', city: 'براك' },
  { id: 'tariq_nahr', name: 'طريق النهر', city: 'أبو غلّاشة' },
  { id: 'nufliyin', name: 'النوفليين', city: 'الدوّان' },
  { id: 'maydan_qadisiya', name: 'ميدان القادسية', city: 'تجي' },
  { id: 'qarra_buli', name: 'القره بولي', city: 'قمّينس' },
  { id: 'qarda', name: 'القرضه', city: 'القطرون' },
  { id: 'sh_qardabia', name: 'ش القرضابية', city: 'بنينا' },
  { id: 'quwida', name: 'القويده', city: 'ككلة' },
  { id: 'rahba', name: 'الرحبة', city: 'الرحيبات' },
  { id: 'hay_salam', name: 'حي السلام', city: 'سوكنة' },
  { id: 'hay_andalus', name: 'حي الاندلس', city: 'ماسة' },
  { id: 'hay_intisar', name: 'حي الانتصار', city: 'بن جواد' },
  { id: 'tariq_shawk', name: 'طريق الشوك', city: 'أم الأرانب' },
  { id: 'sabiaa', name: 'السبيعة', city: 'جادو' },
  { id: 'tawisha', name: 'الطويشة', city: 'غدامس' },
  { id: 'hay_akwakh', name: 'حي الاكواخ', city: 'الرابطة' },
  { id: 'arada', name: 'عرادة', city: 'غات' },
  { id: 'sh_sarim', name: 'ش الصريم', city: 'الأبرق' },
  { id: 'siraj_sharqia', name: 'السراج الشرقية', city: 'سيدي السعيد' },
  { id: 'hay_zuhur', name: 'حي الزهور', city: 'الرجبان' },
  { id: 'hay_islami', name: 'حي الإسلامي', city: 'أوجله' },
  { id: 'awlad_mahmud', name: 'أولاد محمود', city: 'رأس الحمام' },
  { id: 'ayn_zara', name: 'عين زارة', city: 'طلميثة' },
  { id: 'bab_akkara', name: 'باب عكارة', city: 'زلة' },
  { id: 'bab_bin_ghashir', name: 'باب بن غشير', city: 'وادي عطبة' },
  { id: 'badr', name: 'بدر', city: 'البركات' },
  { id: 'sh_baghdad', name: 'ش بغداد', city: 'مرتوبة' },
  { id: 'dawa_islamiya', name: 'الدعوة الإسلامية', city: 'تراغن' },
  { id: 'bir_ghanam', name: 'بئر غنم', city: 'الحشان' },
  { id: 'bin_dakhil', name: 'بن دخيل', city: 'البيضاء' },
  { id: 'bin_yunus', name: 'بن يونس', city: 'قيقاب' },
  { id: 'bin_ashur', name: 'بن عاشور', city: 'المشاشية' },
  { id: 'sh_jakarta', name: 'ش جاكارتا', city: 'بو فاخرة' },
  { id: 'benghazi_jadida', name: 'بنغازي الجديدة', city: 'مساعد' },
  { id: 'janzur', name: 'جنزور', city: 'تاكنس' },
  { id: 'bilyun', name: 'بليون', city: 'سوسة' },
  { id: 'kabaw', name: 'كاباو', city: 'وادي زمزم' },
  { id: 'kashlaf', name: 'كشلاف', city: 'بطة' },
  { id: 'buhadima', name: 'بوهديمة', city: 'تازربو' },
  { id: 'labda', name: 'لبدة', city: 'الجديد' },
  { id: 'masghura', name: 'مصغورة', city: 'فرزوغة' },
  { id: 'hay_dimashq', name: 'حي دمشق', city: 'قرية عمر المختار' },
  { id: 'majabra', name: 'المجابرة', city: 'بئر الأشهب' },
  { id: 'sh_muhammad_maqrif', name: 'شارع محمد المقريف', city: 'ميزران' },
  { id: 'injila', name: 'إنجيلة', city: 'إنجيلة' },
  { id: 'majabra_jadida', name: 'مجابرة الجديدة', city: 'مجابرة الجديدة' },
  { id: 'sh_omar_mukhtar', name: 'ش عمر المختار', city: 'ش عمر المختار' },
  { id: 'qasr_bin_ghashir', name: 'قصر بن غشير', city: 'قصر بن غشير' },
  { id: 'qasr_khayar', name: 'قصر الخيار', city: 'قصر الخيار' },
  { id: 'ras_hassan', name: 'راس حسن', city: 'راس حسن' },
  { id: 'ras_ubayda', name: 'راس عبيدة', city: 'راس عبيدة' },
  { id: 'salah_adin', name: 'صلاح الدين', city: 'صلاح الدين' },
  { id: 'qarya_salih', name: 'قرية صالح', city: 'قرية صالح' },
  { id: 'sidi', name: 'السيدي', city: 'السيدي' },
  { id: 'sidi_misri', name: 'سيدي المصري', city: 'سيدي المصري' },
  { id: 'sh_shawqi', name: 'شارع شوقي', city: 'شارع شوقي' },
  { id: 'sidi_hussein', name: 'سيدي حسين', city: 'سيدي حسين' },
  { id: 'sidi_khalifa', name: 'سيدي خليفة', city: 'سيدي خليفة' },
  { id: 'suq_juma', name: 'سوق الجمعة', city: 'سوق الجمعة' },
  { id: 'salmani', name: 'سلماني', city: 'سلماني' },
  { id: 'suq_khamis', name: 'سوق الخميس', city: 'سوق الخميس' },
  { id: 'maydan_tahrir', name: 'ميدان التحرير', city: 'ميدان التحرير' },
  { id: 'tajura', name: 'تاجوراء', city: 'تاجوراء' },
  { id: 'tariq_sur', name: 'طريق السور', city: 'طريق السور' },
  { id: 'tariq_shat', name: 'طريق الشط', city: 'طريق الشط' },
  { id: 'tamzin', name: 'طمزين', city: 'طمزين' },
  { id: 'tarsana', name: 'ترسانة', city: 'ترسانة' },
  { id: 'tiji', name: 'تيجي', city: 'تيجي' },
  { id: 'fenisia', name: 'فنيسيا', city: 'فنيسيا' },
  { id: 'wadan', name: 'الودان', city: 'الودان' },
  { id: 'wazin', name: 'وازن', city: 'وازن' },
  { id: 'sh_zawiya', name: 'شارع الزاوية', city: 'شارع الزاوية' },
  { id: 'zawiyat_mahjub', name: 'زاوية المحجوب', city: 'زاوية المحجوب' },
  { id: 'zawiyat_dahmani', name: 'زاوية الدهماني', city: 'زاوية الدهماني' },
  { id: 'zanata', name: 'زناتة', city: 'زناتة' },
  { id: 'zuwitina', name: 'زويتينة', city: 'زويتينة' },
  { id: 'madina_qadima', name: 'المدينة القديمة', city: 'المدينة القديمة' },
  { id: 'bayfi', name: 'البيفي', city: 'البيفي' },
  { id: 'kaam', name: 'كعام', city: 'كعام' },
  { id: 'sawalim', name: 'السوالم', city: 'السوالم' }
];

// Helper functions for areas
export const getAreaById = (areaId: string): LibyanArea | undefined => {
  return libyanAreas.find(area => area.id === areaId);
};

export const getAreasByCity = (cityName: string): LibyanArea[] => {
  return libyanAreas.filter(area => area.city === cityName);
};

export const searchAreas = (query: string): LibyanArea[] => {
  return libyanAreas.filter(area =>
    area.name.toLowerCase().includes(query.toLowerCase()) ||
    area.city?.toLowerCase().includes(query.toLowerCase())
  );
};
